### PR TITLE
Switched to using AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Switched to using AsyncKeyedLock, which provides better performance, reduced allocations and does not retain items in the dictionary.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@microsoft-github-policy-service agree

**Comment by MarkCiliaVincenti** [comment]
@evachen96 @mikaelweave

**Comment by MarkCiliaVincenti** [comment]
@vmsuthar56

**Comment by vmsuthar56** [comment]
Hi @MarkCiliaVincenti,
Sorry for late reply and thanks for creating PR.

Could you please tell us about the issue you encountered in the current implementation and as a solution you implemented AsyncKeyedLock? 

Also, if you have done some testing, could you please share your test data and its result?

**Comment by MarkCiliaVincenti** [comment]
> Hi @MarkCiliaVincenti, Sorry for late reply and thanks for creating PR.
> 
> Could you please tell us about the issue you encountered in the current implementation and as a solution you implemented AsyncKeyedLock?
> 
> Also, if you have done some testing, could you please share your test data and its result?

The current implementation permanently retains items in the `private readonly ConcurrentDictionary<string, SemaphoreSlim> keyLocker` and will also create a new `SemaphoreSlim` object every time a new key is used. Benchmarks on performance will largely depend on the actual use, and how many (and how often) new keys are locked on.

**Comment by vmsuthar56** [comment]
Due to the sensitivity of our customers' data, we've chosen to keep our dependency list small. While we see the improvements in your package and acknowledge the performance gain, we would rather improve this without increasing the size of our dependency list.

**Comment by MarkCiliaVincenti** [comment]
I understand, OK.

**Pull request closed without merging**
